#!/usr/bin/env python3
"""
build_pin_schedule.py

Turn the pin library (marketing/pinterest_kit/pins.csv) into a concrete,
follow-it-by-hand posting calendar. Pinterest rewards steady, daily
pinning far more than bursts, so this spreads the library across N days
at fixed times, and orders pins so that:

  * higher-priority pins go out first,
  * the same board isn't hit twice in a row within a day,
  * the same article's variants don't land on the same day.

Outputs (both gitignored-safe, written to marketing/pinterest_kit/):
  posting_schedule.csv  — one row per slot, every field ready to paste,
                          importable into most schedulers.
  posting_schedule.md   — same thing grouped by day, easy to follow by hand.

Usage:
  python build_pin_schedule.py                 # 5/day, default times
  python build_pin_schedule.py --per-day 3
  python build_pin_schedule.py --start 2026-07-01 --tz "JST (UTC+9)"
"""

from __future__ import annotations

import argparse
import csv
from datetime import date, datetime, timedelta
from pathlib import Path

REPO = Path(__file__).resolve().parent
PINS_CSV = REPO / "marketing" / "pinterest_kit" / "pins.csv"
OUT_CSV = REPO / "marketing" / "pinterest_kit" / "posting_schedule.csv"
OUT_MD = REPO / "marketing" / "pinterest_kit" / "posting_schedule.md"

# Good general-purpose Pinterest slots (local time). Evenings/commutes skew
# high for travel-planning intent; adjust with --times if you have analytics.
DEFAULT_TIMES = ["09:00", "12:00", "15:00", "18:00", "21:00"]


def load_pins() -> list[dict]:
    with PINS_CSV.open(encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    # priority: lower number = post sooner. Missing → 5.
    for r in rows:
        try:
            r["_prio"] = int(r.get("priority") or 5)
        except ValueError:
            r["_prio"] = 5
    return rows


def order_pins(pins: list[dict], per_day: int) -> list[dict]:
    """Greedy ordering: by priority, then interleave so consecutive pins
    avoid repeating a board, and same-article variants are spaced out."""
    pool = sorted(pins, key=lambda r: (r["_prio"], r["slug"]))
    ordered: list[dict] = []
    last_board = None
    # track article base (slug without -w2/-w3/-photo suffix) recency
    recent_articles: list[str] = []

    def art_key(r: dict) -> str:
        return r["article_url"]

    while pool:
        pick = None
        for i, cand in enumerate(pool):
            board = cand.get("board_primary", "")
            art = art_key(cand)
            # prefer a pin that doesn't repeat the last board and whose
            # article hasn't appeared in the last (per_day-1) picks
            if board != last_board and art not in recent_articles[-(per_day - 1 or 1):]:
                pick = pool.pop(i)
                break
        if pick is None:  # constraints too tight near the end — just take first
            pick = pool.pop(0)
        ordered.append(pick)
        last_board = pick.get("board_primary", "")
        recent_articles.append(art_key(pick))
    return ordered


def build_schedule(pins: list[dict], start: date, per_day: int, times: list[str]) -> list[dict]:
    ordered = order_pins(pins, per_day)
    schedule = []
    day_index = 0
    slot_in_day = 0
    for pin in ordered:
        if slot_in_day >= per_day:
            slot_in_day = 0
            day_index += 1
        when_date = start + timedelta(days=day_index)
        when_time = times[slot_in_day % len(times)]
        schedule.append({
            "scheduled_date": when_date.isoformat(),
            "scheduled_time": when_time,
            "weekday": when_date.strftime("%a"),
            "board": pin.get("board_primary", ""),
            "board_secondary": pin.get("board_secondary", ""),
            "image_path": pin.get("pin_filename", ""),
            "title": pin.get("title", ""),
            "description": pin.get("description", ""),
            "destination_link": pin.get("article_url", ""),
            "priority": pin.get("priority", ""),
        })
        slot_in_day += 1
    return schedule


def write_csv(schedule: list[dict]) -> None:
    cols = ["scheduled_date", "scheduled_time", "weekday", "board", "board_secondary",
            "image_path", "title", "description", "destination_link", "priority"]
    with OUT_CSV.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        for row in schedule:
            w.writerow(row)


def write_md(schedule: list[dict], tz: str) -> None:
    lines = [
        "# Pinterest posting schedule",
        "",
        f"Generated by `build_pin_schedule.py`. Times are **{tz}**.",
        "",
        "How to use: each day, post the listed pins at the given times. Upload the "
        "image file, paste the title/description, set the destination link, and choose "
        "the board. Don't edit a pin after posting — Pinterest is still ranking it.",
        "",
        "> Re-run this script after generating a fresh wave of pins to extend the calendar. "
        "Pinterest favours *fresh* pins, so new images for existing articles are encouraged "
        "every few weeks.",
        "",
    ]
    current_date = None
    for row in schedule:
        if row["scheduled_date"] != current_date:
            current_date = row["scheduled_date"]
            lines.append(f"\n## {current_date} ({row['weekday']})\n")
        lines.append(f"### {row['scheduled_time']} — {row['board']}")
        lines.append(f"- **Image:** `{row['image_path']}`")
        lines.append(f"- **Title:** {row['title']}")
        lines.append(f"- **Description:** {row['description']}")
        lines.append(f"- **Link:** {row['destination_link']}")
        if row["board_secondary"]:
            lines.append(f"- **Also pin to:** {row['board_secondary']} (wait a day, fresh pin)")
        lines.append("")
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    p = argparse.ArgumentParser(description="Build a Pinterest posting calendar from pins.csv")
    p.add_argument("--start", default=None, help="start date YYYY-MM-DD (default: tomorrow)")
    p.add_argument("--per-day", type=int, default=5, help="pins per day (default 5)")
    p.add_argument("--times", default=",".join(DEFAULT_TIMES),
                   help="comma-separated HH:MM slots")
    p.add_argument("--tz", default="local time", help="timezone label for the .md header")
    args = p.parse_args()

    start = (datetime.strptime(args.start, "%Y-%m-%d").date()
             if args.start else date.today() + timedelta(days=1))
    times = [t.strip() for t in args.times.split(",") if t.strip()]

    pins = load_pins()
    schedule = build_schedule(pins, start, args.per_day, times)
    write_csv(schedule)
    write_md(schedule, args.tz)

    days = len({r["scheduled_date"] for r in schedule})
    print(f"  pins scheduled : {len(schedule)}")
    print(f"  spread over    : {days} days ({args.per_day}/day at {', '.join(times)})")
    print(f"  csv            : {OUT_CSV.relative_to(REPO)}")
    print(f"  markdown       : {OUT_MD.relative_to(REPO)}")


if __name__ == "__main__":
    main()
