#!/usr/bin/env python3
"""
repurpose_article.py  —  Agent #3: article -> social/video repurposer

Reads a published Travel Now article and emits a ready-to-post bundle so
one piece of writing fuels Pinterest, X, short-form video, and YouTube
without rewriting anything by hand. No external API — it parses the HTML
we already publish.

Output: marketing/repurposed/<slug>.md  containing:
  * 3 fresh Pinterest pin descriptions (different angles) + board ideas
  * an X / Twitter thread (hook -> points -> CTA)
  * a 35-second short-video script (hook / beats / CTA, with on-screen text)
  * a YouTube / Shorts description + hashtags

Usage:
  python repurpose_article.py --slug airalo-vs-holafly-vs-saily
  python repurpose_article.py --path site/cities/tokyo/asakusa.html
  python repurpose_article.py --all          # every article in site/articles
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from bs4 import BeautifulSoup

REPO = Path(__file__).resolve().parent
SITE = REPO / "site"
OUT_DIR = REPO / "marketing" / "repurposed"

SKIP_HEADINGS = {
    "keep reading on travel now", "related", "related guides", "related reading",
    "related travel prep", "related articles", "references & sources",
    "references and sources", "sources & further reading", "where to go next on travel now",
    "liked this guide? get one like it, every week.", "get country profiles like this in your inbox.",
    "get city guides like this in your inbox.", "want guides like this in your inbox?",
}


def first_sentence(text: str) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    m = re.split(r"(?<=[.!?]) ", text)
    return m[0].strip() if m else text


def extract(html: str) -> dict:
    soup = BeautifulSoup(html, "html.parser")
    title = (soup.find("h1").get_text(strip=True) if soup.find("h1")
             else (soup.title.get_text(strip=True) if soup.title else "Travel Now guide"))
    canon = soup.find("link", rel="canonical")
    url = canon["href"] if canon and canon.has_attr("href") else ""
    desc_tag = soup.find("meta", attrs={"name": "description"})
    description = desc_tag["content"] if desc_tag and desc_tag.has_attr("content") else ""

    # sections: H2 -> first sentence of the following paragraph
    sections: list[tuple[str, str]] = []
    for h2 in soup.find_all("h2"):
        htext = h2.get_text(strip=True)
        if htext.lower() in SKIP_HEADINGS or not htext:
            continue
        para = ""
        sib = h2.find_next_sibling()
        hops = 0
        while sib is not None and hops < 4:
            if sib.name == "p":
                para = first_sentence(sib.get_text(" ", strip=True))
                break
            sib = sib.find_next_sibling()
            hops += 1
        sections.append((htext, para))

    # FAQ pairs
    faqs: list[tuple[str, str]] = []
    for det in soup.select("details"):
        s = det.find("summary")
        p = det.find("p")
        if s and p:
            faqs.append((s.get_text(strip=True), first_sentence(p.get_text(" ", strip=True))))

    lede = ""
    lede_tag = soup.find(class_="article-lede")
    if lede_tag:
        lede = first_sentence(lede_tag.get_text(" ", strip=True))

    return {"title": title, "url": url, "description": description,
            "sections": sections, "faqs": faqs, "lede": lede}


def hashtags(title: str) -> str:
    base = ["#TravelTips", "#TravelPrep", "#TravelHacks"]
    t = title.lower()
    if "esim" in t or "sim" in t or "wifi" in t:
        base += ["#eSIM", "#TravelTech"]
    if "insurance" in t:
        base += ["#TravelInsurance", "#DigitalNomad"]
    if "airport" in t or "security" in t or "carry" in t or "pack" in t:
        base += ["#PackingTips", "#CarryOn"]
    if "japan" in t or "tokyo" in t or "korea" in t or "vietnam" in t or "asia" in t:
        base += ["#Japan", "#AsiaTravel"]
    if "adapter" in t or "plug" in t or "power" in t:
        base += ["#TravelAdapter"]
    # de-dup, keep order, cap at 6
    seen, out = set(), []
    for h in base:
        if h.lower() not in seen:
            seen.add(h.lower()); out.append(h)
    return " ".join(out[:6])


def build_bundle(d: dict) -> str:
    title, url, desc = d["title"], d["url"], d["description"]
    secs = [s for s in d["sections"] if s[0]][:6]
    faqs = d["faqs"][:6]
    points = [h for h, _ in secs] or [q for q, _ in faqs]
    tags = hashtags(title)
    title_hook = re.sub(r"[.!?]+$", "", title).strip()
    L: list[str] = []

    L.append(f"# Repurpose bundle — {title}\n")
    L.append(f"Source: {url}\n")
    L.append("> Generated by `repurpose_article.py`. Copy-paste each block; tweak the voice "
             "to taste. Schedule, don't dump them all at once.\n")

    # ---- Pinterest ----
    L.append("\n## Pinterest — 3 fresh pin descriptions\n")
    angles = [
        ("Straight value", desc or (secs[0][1] if secs else title)),
        ("Listicle hook", "Save this before your next trip — "
            + (", ".join(p.rstrip('.').lower() for p, _ in secs[:3]) if secs else "the essentials")
            + ". Full guide linked."),
        ("Question hook", f"{title_hook}? Here's the honest answer, "
            "with the details that actually change your decision. Read the full guide."),
    ]
    for i, (name, body) in enumerate(angles, 1):
        L.append(f"**Pin {i} — {name}**")
        L.append(f"- Title: {title}")
        L.append(f"- Description: {body}")
        L.append(f"- Link: {url}")
        L.append("")

    # ---- X thread ----
    L.append("\n## X / Twitter thread\n")
    L.append(f"1/ {title_hook} — the version I wish someone had given me. 🧵")
    n = 2
    for h, p in (secs or [(q, a) for q, a in faqs])[:5]:
        line = f"{h}." if not p else f"{h}: {p}"
        L.append(f"{n}/ {line}")
        n += 1
    L.append(f"{n}/ Full breakdown (free, no fluff): {url}\n\n{tags}")

    # ---- Short video ----
    L.append("\n## Short-form video script (~35s, Reels / TikTok / Shorts)\n")
    hook = title_hook
    L.append("| Time | On-screen text | Voiceover |")
    L.append("|---|---|---|")
    L.append(f"| 0–3s | {hook}? | \"If you're about to travel, save this.\" |")
    beats = (secs or [(q, a) for q, a in faqs])[:4]
    t0 = 3
    for h, p in beats:
        t1 = t0 + 7
        vo = p if p else h
        L.append(f"| {t0}–{t1}s | {h} | \"{vo}\" |")
        t0 = t1
    L.append(f"| {t0}–{t0+4}s | Full guide → link in bio | \"The full guide's linked — it's free.\" |")
    L.append("\n*Shoot: text-on-screen over b-roll (airport, phone, packing). Caption the whole thing — most watch muted.*")

    # ---- YouTube ----
    L.append("\n## YouTube / Shorts description\n")
    L.append(f"{title}\n")
    L.append(f"{desc}\n")
    L.append(f"Full written guide: {url}\n")
    L.append(tags)

    return "\n".join(L) + "\n"


def repurpose_path(path: Path) -> Path:
    html = path.read_text(encoding="utf-8")
    d = extract(html)
    slug = path.stem if path.stem != "index" else path.parent.name
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUT_DIR / f"{slug}.md"
    out.write_text(build_bundle(d), encoding="utf-8")
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--slug", help="article slug in site/articles/")
    g.add_argument("--path", help="explicit path to an HTML file")
    g.add_argument("--all", action="store_true", help="every article in site/articles/")
    args = ap.parse_args()

    if args.all:
        paths = sorted((SITE / "articles").glob("*.html"))
    elif args.slug:
        paths = [SITE / "articles" / f"{args.slug}.html"]
    else:
        paths = [REPO / args.path]

    for p in paths:
        if not p.exists():
            print(f"  ⚠ missing: {p}")
            continue
        out = repurpose_path(p)
        print(f"  ✓ {p.name} -> {out.relative_to(REPO)}")


if __name__ == "__main__":
    main()
